service: test-serverless

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  profile: karengaspan
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - s3:GetObject
            - s3:PutObject
          Resource:
            - 'arn:aws:s3:::holidayswap-local'
            - 'arn:aws:s3:::holidayswap-local/*'
functions:
  lambda-s3-image-handler:
    handler: index.handler
    timeout: 10
